### ISSUE TITLE
eslint:recommended rules not being applied

### ISSUE THREAD

**Issue by desandro** [fictivekin/eslint-config-fk#1]
@jacobfentress I just discovered the rules from `eslint:recommended` are not being applied. In particular, I had an undefined variable that was not caught as [`no-undef`](https://eslint.org/docs/rules/no-undef) was not set.

Turns out that extending the [google config enables Google's rules](https://github.com/google/eslint-config-google#using-the-google-config-with-eslintrecommended), but it does not extend `eslint:recommended` itself.

> There are several rules in the eslint:recommended ruleset that Google style is not opinionated about that you might want to enforce in your project.

**Solution 1** - extend `eslint:recommended` in our `index.js`

``` js
// @fictivekin/eslint-config-fk/index.js
  "extends": [
    "eslint:recommended",
    "google"
  ],
```

**Solution 2** - Edit README to recommend extending `eslint:recommended` also side usage of `@fictivekin/eslint-config-fk` in project ESLint config

``` json
// README json example
"eslintConfig": {
    "extends": [
      "eslint:recommended",
      "@fictivekin/eslint-config-fk"
    ]
}
```

LMK how you'd like to proceed.

**Comment by jakefentress** [comment]
@desandro oooh, that's a great catch.

Personally, I'm ok with either solution. If there is one you feel better about, please run with it. Let me know when if you update the index.js of this project (and when you're ready) and I'll be happy to bump the version on npm.

**Comment by desandro** [comment]
I recommend **Solution 1** - extend `eslint:recommended` in our `index.js`. This feels more fool-proof. I'd say it would require a major version bump as lots of other errors could be thrown by eslint once enabled.

I'd do it myself, but looks like I need `push` access

**Comment by jakefentress** [comment]
oof. You should have `push` access, now.

**Comment by desandro** [comment]
Pushed. Looks like you'll have to do the `npm publish`
