### ISSUE TITLE
Consider adding dependency import/require sorting rule

### ISSUE THREAD

**Issue by ashur** [fictivekin/eslint-config-fk#6]
## Summary

Using an ESLint rule to define how dependency `import` or `require` statements should be sorted could help make those blocks more consistent throughout a project, especially when fixes are applied automatically by a user's editor.

## Links

ESLint plugins we might consider:

- [`sort-imports-requires`](https://www.npmjs.com/package/eslint-plugin-sort-imports-requires) (`import` and `require`; actively maintained, lightly used)
- [`simple-import-sort`](https://www.npmjs.com/package/eslint-plugin-simple-import-sort) (`import` only; actively maintained, heavily used)
- [`sort-requires`](https://www.npmjs.com/package/eslint-plugin-sort-requires) (`require` only; no longer maintained, heavily used)

## Considerations

- Should `eslint-config-fk` support both ESM `import` and CJS `require` statements, or prefer just one?

**Comment by desandro** [comment]
Re import vs require: https://masteringjs.io/tutorials/node/import-vs-require

**Comment by nerdpruitt** [comment]
I like having a rule around this. We could go with [simple-import-sort](https://www.npmjs.com/package/eslint-plugin-simple-import-sort) and just ignore it for `require` (if it's enough of an edge case).

**Comment by desandro** [comment]
Let's add `simple-import-sort`. Assigning to Ashur.

**Comment by desandro** [comment]
Closed by #10
