### ISSUE TITLE
Ditch google config

### ISSUE THREAD

**Issue by desandro** [fictivekin/eslint-config-fk#8]
[Google config](https://github.com/google/eslint-config-google) has not been updated in 2.5 years. It may be easier to copy/paste it over rather than using it as the default.

**Comment by jakefentress** [comment]
makes sense! Most of this is really quite old and could stand dusting off.

**Comment by desandro** [comment]
Options

1. Copy/paste google config for now
2. Use different base dependency - Standard js, https://github.com/standard/eslint-config-standard

@nerdpruitt please look into Standard JS

**Comment by desandro** [comment]
Feels right. I'm going remove the google extension.
