### ISSUE TITLE
Remove globals

### ISSUE THREAD

**Issue by desandro** [fictivekin/eslint-config-fk#9]
``` js
  "globals": {
    "__DEV__": false,
    "alert": false,
    "describe": false,
    "document": false,
    "it": false,
    "expect": false,
    "navigator": false,
    "FormData": false,
    "window": false
  }
```

- `__DEV__` - not in 11ty bootstrap
- `alert`, `document`, `window`, `navigator` - add `env: { browser: true }` instead
- `describe`, `it`, `expect` - these are testing globals. These should be added per project, when we do have testing
- `FormData` - looks like leftover from an integration

I recommend removing all these and adding `env: { browser: true }`. 95% of our repos are browser projects, so this feels like the right choice.

**Comment by dacohenii** [comment]
Agreed: kill them all and add back individually as necessary on a case by case basis
